version: '3.8'
services:
  configserver:
    image: polawarkirand/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - polawarkirand-network
    environment:
      SPRING_PROFILES_ACTIVE: dev
  eurekaserver:
    image: polawarkirand/eurekaserver:latest
    mem_limit: 700m
    ports:
    - 8761:8761
    networks:
    - polawarkirand-network
    depends_on:
    - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/  
  accounts:
    image: polawarkirand/accounts:latest
    mem_limit: 700m
    ports:
    - 8080:8080
    networks:
    - polawarkirand-network
    depends_on:
     - configserver
     - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
  loans:
    image: polawarkirand/loans:latest
    mem_limit: 700m
    ports:
    - 8090:8090
    networks:
    - polawarkirand-network
    depends_on:
    - configserver
    - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
  cards:
    image: polawarkirand/cards:latest
    mem_limit: 700m
    ports:
    - 9000:9000
    networks:
    - polawarkirand-network
    depends_on:
     - configserver
     - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
  gatewayserver:
    image: polawarkirand/gatewayserver:latest
    mem_limit: 700m
    ports:
    - 8072:8072
    networks:
    - polawarkirand-network
    depends_on:
    - configserver
    - eurekaserver
    - cards
    - loans
    - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
networks:
  polawarkirand-network: 